
%{
#include <string.h>

#define YYSTYPE char*

%}

%start input

%token

%% /* Grammar rules and actions follow */
input:
		   /* empty */
;

%%/* A lexical scanner generated by flex */
